env:
  es6: true
  node: true
extends: [
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
],
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
